### ISSUE TITLE
[v10] Purchase Discount  error Discount calculation

### ISSUE THREAD

**Issue by bunhin** [OCA/purchase-workflow#530] opened 2018-03-25 17:19 UTC
I found inconsistent calculation error with the discount
![image](https://user-images.githubusercontent.com/7310629/37877877-14f7db36-308b-11e8-9a3d-fdbc877f0eb1.png)
Please find on the picture,  i do not know why this kind of error is happen.

Look intu the line with 5% discount  the calculation is not correct i believe

Please have a look

**Comment by pedrobaeza** [comment] 2018-03-25 17:25
Please try to reproduce the problem in runbot.

**Comment by bunhin** [comment] 2018-03-25 17:37
I try with other database  the 5% discount calculation is correct, what could be wrong?

**Comment by pedrobaeza** [comment] 2018-03-25 17:40
Do you have your module updated with latest code?

**Comment by bunhin** [comment] 2018-03-25 17:48
may not to the last date but i will try to update now,  here i try another RFQ and it seem the inconsistent error is reproduced for the 5% discount

![image](https://user-images.githubusercontent.com/7310629/37878194-41fbba5e-308f-11e8-9b18-0fdae469831a.png)

but i try to update the code and then come back

**Comment by pedrobaeza** [comment] 2018-03-25 17:59
Then we have the answer. There were an update recently. Closing until further notice.

**Closed as completed by pedrobaeza** 2018-03-25 17:59 UTC

**Comment by bunhin** [comment] 2018-03-25 18:29
dear @pedrobaeza 
I just stop the server, update odoo with git pull,  update oca/purchase-workflow/  with git pull,  start again the server

login aggain to database, dan update, epdate module list,  than try to make another purchase rfq

it still happen,  is itthe update steps is not enough?
here is latest result after the above update
![image](https://user-images.githubusercontent.com/7310629/37878517-b6dd4a0e-3094-11e8-837e-52c95eb918db.png)

now i extend to other number for discount, 5%, and 7%  get the calculation error

please inform if the update is not enough, or the most effective way to update

if it is because of the code, but why not all discount got error?  is it related with decimal rounding?

thank you

**Comment by pedrobaeza** [comment] 2018-03-25 18:33
Sorry, but you need to reproduce it in runbot for being traceable. I'm figuring out that the problem is with other custom module you have in your DB.

**Comment by bunhin** [comment] 2018-03-25 18:39
ok, will try to run bot,  only purchase discount of OCA, multi-company OCA, mis buileder OCA, and backend debranding  -IT-Projects 

thank you anyway for response. will go to runbot
