### ISSUE TITLE
[13.0] procurement_purchase_no_grouping will group PO lines in one RFQ even if two different suppliers are set on the products

### ISSUE THREAD

**Issue by tarbib** [OCA/purchase-workflow#975] opened 2020-09-11 16:33 UTC
Steps to reproduce (tested on OCA runbot) :
Allow "MTO" and "Buy" routes on product categories
![image](https://user-images.githubusercontent.com/2255433/92950018-5052e580-f45c-11ea-8359-aa9c2ac7ad40.png)

"Procured purchase grouping | No order grouping" on Category "All"

![image](https://user-images.githubusercontent.com/2255433/92949878-15e94880-f45c-11ea-9ab6-95fcb00a8f41.png)

Create two products :
Memo 1 (Supplier One) and Memo 2 (Supplier Two)
![image](https://user-images.githubusercontent.com/2255433/92950395-d96a1c80-f45c-11ea-90b2-f1d2a35c1ec9.png)

![image](https://user-images.githubusercontent.com/2255433/92950357-ce16f100-f45c-11ea-9e4d-b950164cc7d9.png)

Create a SO with the two above products:
![image](https://user-images.githubusercontent.com/2255433/92950514-0cacab80-f45d-11ea-8e09-4f4874a2a504.png)

Issue : 
Only one RFQ is created for one of the suppliers.
![image](https://user-images.githubusercontent.com/2255433/92950568-2cdc6a80-f45d-11ea-935b-c01fa325c68b.png)

![image](https://user-images.githubusercontent.com/2255433/92950583-349c0f00-f45d-11ea-92ba-ca37d32d882d.png)

**Comment by tarbib** [comment] 2020-09-11 16:35
@Tardo 
Hello! First thanks a lot for the migration of this module.
I have this issue with no grouping setting at the moment. 
Any idea on how to fix it?
Thanks

**Comment by pedrobaeza** [comment] 2020-09-11 16:53
Are you sure the problem is with this module? What happen in a vanilla Odoo? Are you able to reproduce the problem in the demo runbot instance provided for the module?

**Comment by tarbib** [comment] 2020-09-14 07:13
@pedrobaeza 
Hello Pedro, yes I am sure. When I try on a vanialla Odoo or use "standard grouping" option on OCA runbot then it will create two POs. My screenshots are taken from the demo runbot instance provided for the module.

**Comment by tarbib** [comment] 2020-09-15 07:48
Hello @pedrobaeza 
In order to make 100% sure, I deployed an odoo.sh instance with only procurement_purchase_no_grouping as OCA module installed. Result is the same.
You can see my test [here](https://slack-files.com/T3WUKRESJ-F01B28B5UUR-6f66707d49).
Thanks

**Comment by pedrobaeza** [comment] 2020-09-15 07:49
Yes, I can confirm the problem. I'm analyzing now.

**Comment by pedrobaeza** [comment] 2020-09-15 08:37
Fixed in 8d36751

**Closed as completed by pedrobaeza** 2020-09-15 08:37 UTC

**Comment by tarbib** [comment] 2020-09-22 09:34
Hello @pedrobaeza 
I tested another configuration, and I am wondering if the result is really the intended result.
I have set Vendor 1 to both Memo 1 and Memo 2 products.
We get two different RFQ for the same vendor. One for the product Memo 1 and one for the product Memo 2.
So Odoo creates one RFQ per procurement line even though it's for the same supplier.
https://slack-files.com/T3WUKRESJ-F01B1RN9KU5-4922541618
I would have thought that in this case it would group the lines per vendor if they are from the same procurement group.
What do you think?

**Comment by pedrobaeza** [comment] 2021-01-25 16:20
@tarbib I think the patch from #1080 (which is for 12.0, but it will be applied on 13.0), fixes your problem.

**Comment by tarbib** [comment] 2021-01-26 17:26
@pedrobaeza thanks Pedro for the followup!
