### ISSUE TITLE
purchase_order_revision...issue question

### ISSUE THREAD

**Issue by jaronemo** [OCA/purchase-workflow#148] opened 2015-06-23 08:50 UTC
cancel purchase order.Number: PO1505050001
click new resvision button...show error..

![image](https://cloud.githubusercontent.com/assets/8476734/8302276/ce79f8c4-19c7-11e5-87d7-9cb11e92196f.png)

and odoo server log ...

![image](https://cloud.githubusercontent.com/assets/8476734/8302293/ecfe9732-19c7-11e5-9fd3-ef57d1b58ab7.png)

**Comment by pedrobaeza** [comment] 2015-06-23 15:42
This is due to there's no post-install script to assign `unrevisioned_name` field on existing purchase orders. @gurneyalex, @eLBati, can you check it?

**Comment by eLBati** [comment] 2015-06-23 17:31
@jaronemo I can't generate the error on a new DB. Could you provide the steps to reproduce it?

@gurneyalex however, I found a problem with `unrevisioned_name` as pointed out by https://github.com/OCA/purchase-workflow/pull/149: `unrevisioned_name` is always False. How is it supposed to be set?

**Comment by jaronemo** [comment] 2015-06-24 02:47
Dear sir

![image](https://cloud.githubusercontent.com/assets/8476734/8321814/4d0d7d3c-1a5e-11e5-82ad-6edfcd658554.png)

![image](https://cloud.githubusercontent.com/assets/8476734/8321817/6b4f23cc-1a5e-11e5-8667-3c5dacd23968.png)

UPDATE "purchase_order" SET "name"='False-01',"revision_number"=1 ... ==> Think this is the problem from any orders.

runing test yaml.....

![image](https://cloud.githubusercontent.com/assets/8476734/8321987/f74414a8-1a60-11e5-9b34-e89033bc1ed1.png)

**Comment by gurneyalex** [comment] 2015-06-24 20:07
@jaronemo I thing #151 may fix your issue (but you will need to manually update you database fix the `False` unrevisionned_name columns. 

Do you confirm?

**Comment by jaronemo** [comment] 2015-06-25 01:50
Dear Sir
1. uninstall purchase_order_revision module
2.  openerp-server -c /etc/odoo-server.conf -u all --stop-after-init -d DB
3. install purchase_order_revision
module is this:
![image](https://cloud.githubusercontent.com/assets/8476734/8345322/eed7f66c-1b1f-11e5-95b0-bb051d5e3626.png)

![image](https://cloud.githubusercontent.com/assets/8476734/8345278/3ebcb268-1b1f-11e5-98a7-715d60b1fd3b.png)

![image](https://cloud.githubusercontent.com/assets/8476734/8345301/964ec49e-1b1f-11e5-9ea8-e3407b52a5b4.png)

![image](https://cloud.githubusercontent.com/assets/8476734/8345306/a796f7d0-1b1f-11e5-9508-82e647102846.png)

**Comment by eLBati** [comment] 2015-06-25 09:47
@jaronemo are you able to generate the error on a new DB? Could you provide the steps to reproduce it?

**Comment by jaronemo** [comment] 2015-06-25 14:43
OK!...I wii do it..!

now..i re-create database name is purchase_test.
step1:
![image](https://cloud.githubusercontent.com/assets/8476734/8358514/2f940952-1b93-11e5-91a0-b1e29cc619c2.png)

step2: (cancel PO00006 Order)
![image](https://cloud.githubusercontent.com/assets/8476734/8358535/4c988870-1b93-11e5-8271-a5ea8d5ff6b4.png)

step3: (error)

![image](https://cloud.githubusercontent.com/assets/8476734/8358549/6643828e-1b93-11e5-9b50-7bb879ea7fdf.png)

step4: trace log

![image](https://cloud.githubusercontent.com/assets/8476734/8358569/870a1320-1b93-11e5-8b93-4ce7dc4480b5.png)

**Comment by eLBati** [comment] 2015-06-29 16:29
@jaronemo it seems your are not using @gurneyalex's fix (https://github.com/OCA/purchase-workflow/pull/151).
Please try with `gurneyalex:8.0-fix_purchase_order_revision` branch or at http://3109713-151-296756.runbot1.odoo-community.org/

**Comment by jaronemo** [comment] 2015-06-30 02:49
Dear Sir...

I'm sure I've replaced the code
I even re-create a new demo database (Purchase_Test)
It remains the same.

![image](https://cloud.githubusercontent.com/assets/8476734/8423000/682e009e-1f15-11e5-94d0-6e30d6f844f5.png)

I linked to the location you provided to test, but also the problem occurred. Although not like me wrong.
![image](https://cloud.githubusercontent.com/assets/8476734/8423018/9289ec36-1f15-11e5-8f5b-c7fab4d80669.png)

**Comment by eLBati** [comment] 2015-07-01 09:20
Just tried on http://3109713-151-296756.runbot1.odoo-community.org/ (DB `3109713-151-296756-base`) the steps
- Created new PO `PO00009`
- Canceled it
- Clicked on 'new revision' (system created `PO00009-01`)
- Canceled and clicked 'new revision' again (system created `PO00009-02`)
- Confirmed `PO00009-02`

So, I am not able to reproduce the problem

**Comment by jaronemo** [comment] 2015-07-01 15:58
Dear Sir..

Sorry..
follow url ..test...
cancel PO00006
clicked on 'new revision' (create false-01..is ok)
cancel PO00002
click ed on 'new revision' (failed...error...please look picture)
![image](https://cloud.githubusercontent.com/assets/8476734/8458956/a0519872-204c-11e5-9946-52d2d2a6a96e.png)

tried on 
![image](https://cloud.githubusercontent.com/assets/8476734/8459007/ee65c1f0-204c-11e5-9b8c-d5ce13b6f25d.png)

tried on 
![image](https://cloud.githubusercontent.com/assets/8476734/8459020/05bdacc8-204d-11e5-8c26-0ed13f13059d.png)
this database...  
is have problem..

**Comment by pedrobaeza** [comment] 2016-04-04 08:00
This is solved in the linked merged PR, so I close.

**Closed as completed by pedrobaeza** 2016-04-04 08:00 UTC
